import { FineData, Language, RightCategory, Translations } from './types';

export const UI_STRINGS: Translations = {
  appName: { en: 'Personal Advocate', hi: 'व्यक्तिगत अधिवक्ता', gu: 'વ્યક્તિગત એડવોકેટ' },
  needHelpNow: { en: 'I Need Help Now', hi: 'मुझे अभी मदद चाहिए', gu: 'મારે અત્યારે મદદ જોઈએ છે' },
  checkFine: { en: 'Check a Fine', hi: 'जुर्माना जांचें', gu: 'દંડ તપાસો' },
  history: { en: 'History', hi: 'इतिहास', gu: 'ઇતિહાસ' },
  knowYourRights: { en: 'Know Your Rights', hi: 'अपने अधिकार जानें', gu: 'તમારા અધિકારો જાણો' },
  home: { en: 'Home', hi: 'होम', gu: 'હોમ' },
  advocate: { en: 'Advocate', hi: 'अधिवक्ता', gu: 'એડવોકેટ' },
  describeSituation: { en: 'Describe your situation here...', hi: 'यहां अपनी स्थिति का वर्णन करें...', gu: 'અહીં તમારી પરિસ્થિતિનું વર્ણન કરો...' },
  send: { en: 'Send', hi: 'भेजें', gu: 'મોકલો' },
  gettingAdvice: { en: 'Getting advice, please wait...', hi: 'सलाह मिल रही है, कृपया प्रतीक्षा करें...', gu: 'સલાહ મળી રહી છે, કૃપા કરીને રાહ જુઓ...' },
  whatToSay: { en: 'What to Say (Politely)', hi: 'क्या कहें (विनम्रता से)', gu: 'શું કહેવું (નમ્રતાથી)' },
  whatToDo: { en: 'What to Do (Your Actions)', hi: 'क्या करें (आपकी क्रियाएं)', gu: 'શું કરવું (તમારી ક્રયાઓ)' },
  whatNotToDo: { en: 'What NOT to Do', hi: 'क्या न करें', gu: 'શું ન કરવું' },
  officialSources: { en: 'Official Sources', hi: 'आधिकारिक स्रोत', gu: 'સત્તાવાર સ્ત્રોતો' },
  selectState: { en: 'Select State', hi: 'राज्य चुनें', gu: 'રાજ્ય પસંદ કરો' },
  searchOffense: { en: 'Search for an offense (e.g., helmet)', hi: 'अपराध खोजें (उदा. हेलमेट)', gu: 'ગુના માટે શોધો (દા.ત. હેલ્મેટ)' },
  noFinesFound: { en: 'No fines found for your search.', hi: 'आपकी खोज के लिए कोई जुर्माना नहीं मिला।', gu: 'તમારી શોધ માટે કોઈ દંડ મળ્યો નથી.' },
  fineDetails: { en: 'Fine Details', hi: 'जुर्माने का विवरण', gu: 'દંડની વિગતો' },
  offense: { en: 'Offense', hi: 'अपराध', gu: 'ગુનો' },
  lawSection: { en: 'Law Section', hi: 'कानून धारा', gu: 'કાયદાની કલમ' },
  fineAmount: { en: 'Fine Amount', hi: 'जुर्माने की राशि', gu: 'દંડની રકમ' },
  paymentProcedure: { en: 'Official Payment Procedure', hi: 'आधिकारिक भुगतान प्रक्रिया', gu: 'સત્તાવાર ચુકવણી પ્રક્રિયા' },
  noHistory: { en: 'Your history is empty.', hi: 'आपका इतिहास खाली है।', gu: 'તમારો ઇતિહાસ ખાલી છે.' },
  view: { en: 'View', hi: 'देखें', gu: 'જુઓ' },
  query: { en: 'Your Query', hi: 'आपकी क्वेरी', gu: 'તમારી ક્વેરી' },
  back: { en: 'Back', hi: 'वापस', gu: 'પાછા' },
  readAloud: { en: 'Read Aloud', hi: 'जोर से पढ़ें', gu: 'મોટેથી વાંચો' },
  stopReading: { en: 'Stop Reading', hi: 'पढ़ना बंद करें', gu: 'વાંચવાનું બંધ કરો' },
  errorOccurred: { en: 'An error occurred. Please try again.', hi: 'एक त्रुटि हुई। कृपया पुन: प्रयास करें।', gu: 'એક ભૂલ આવી. કૃપા કરીને ફરી પ્રયાસ કરો.'},
  showProcedure: { en: 'Show Procedure', hi: 'प्रक्रिया देखें', gu: 'પ્રક્રિયા જુઓ' },
  hideProcedure: { en: 'Hide Procedure', hi: 'प्रक्रिया छिपाएं', gu: 'પ્રક્રિયા છુપાવો' },
  viewingHistory: { en: 'Viewing Past Advice', hi: 'पिछली सलाह देखना', gu: 'ભૂતકાળની સલાહ જોવી' },
};

export const SYSTEM_PROMPT = (language: Language): string => {
  const langMap: Record<Language, string> = {
      en: 'English',
      hi: 'Hindi',
      gu: 'Gujarati'
  };
  return `You are an AI legal advocate for Indian citizens in a high-stress confrontation with authority (e.g., police). Your response MUST be extremely concise, direct, and easy to read in a panic. Use simple language.

- **Source**: Base your advice ONLY on the provided official Google Search results.
- **Format**: Use this exact markdown structure. Use bullet points ('-') for every piece of advice.
    '### What to Say (Politely)'
    '### What to Do (Your Actions)'
    '### What NOT to Do'
- **Content Style**:
    - Give short, command-like instructions (e.g., "State your name clearly.", "Do not argue.").
    - If the authority demands a bribe, explicitly state it is illegal and provide the correct procedure (e.g., "Do not pay cash. Ask for an official e-challan.").
    - If the authority is violent, advise on de-escalation and seeking help later (e.g., "Do not physically resist. Note their badge number. Report the incident later.").
- **Language**: Respond ONLY in ${langMap[language]}.`;
}

export const FINE_DATA: FineData = {
    "Delhi": [
        { offense: { en: 'Driving without helmet', hi: 'बिना हेलमेट के गाड़ी चलाना', gu: 'હેલ્મેટ વિના ડ્રાઇવિંગ' }, section: '194D MVA', fine: '₹1,000 and/or disqualification of license for 3 months', procedure: { en: 'The officer will issue an e-challan. Do not pay cash without a receipt. They cannot impound the vehicle for this offense alone. Both rider and pillion must wear a helmet.', hi: 'अधिकारी ई-चालान जारी करेगा। बिना रसीद के नकद भुगतान न करें। वे केवल इस अपराध के लिए वाहन को जब्त नहीं कर सकते। राइडर और पिलियन दोनों को हेलमेट पहनना चाहिए।', gu: 'અધિકારી ઇ-ચલન જારી કરશે. રસીદ વિના રોકડ ચૂકવશો નહીં. તેઓ ફક્ત આ ગુના માટે વાહન જપ્ત કરી શકતા નથી. રાઇડર અને પિલિયન બંનેએ હેલ્મેટ પહેરવું આવશ્યક છે.' } },
        { offense: { en: 'Driving without seatbelt', hi: 'बिना सीटबेल्ट के गाड़ी चलाना', gu: 'સીટબેલ્ટ વિના ડ્રાઇવિંગ' }, section: '194B(1) MVA', fine: '₹1,000', procedure: { en: 'An e-challan will be issued. The fine applies to all passengers required to wear a seatbelt, including those in the rear seats.', hi: 'एक ई-चालान जारी किया जाएगा। यह जुर्माना उन सभी यात्रियों पर लागू होता है जिन्हें सीटबेल्ट पहनना आवश्यक है, जिसमें पीछे की सीटों वाले भी शामिल हैं।', gu: 'ઇ-ચલન જારી કરવામાં આવશે. આ દંડ તે બધા મુસાફરોને લાગુ પડે છે જેમને સીટબેલ્ટ પહેરવાની જરૂર છે, પાછળની સીટ પર બેઠેલા લોકો સહિત.' } },
        { offense: { en: 'Driving without License', hi: 'बिना लाइसेंस के गाड़ी चलाना', gu: 'લાયસન્સ વિના ડ્રાઇવિંગ' }, section: '3/181 MVA', fine: '₹5,000', procedure: { en: 'Police may impound the vehicle if you cannot produce a valid license. You have the right to show a digital copy from DigiLocker or mParivahan. You get a 15-day window to produce the original document.', hi: 'यदि आप वैध लाइसेंस प्रस्तुत नहीं कर सकते तो पुलिस वाहन को जब्त कर सकती है। आपको डिजिलॉकर या एम-परिवहन से डिजिटल कॉपी दिखाने का अधिकार है। आपको मूल दस्तावेज़ प्रस्तुत करने के लिए 15 दिन का समय मिलता है।', gu: 'જો તમે માન્ય લાયસન્સ રજૂ ન કરી શકો તો પોલીસ વાહન જપ્ત કરી શકે છે. તમને ડીજીલોકર અથવા એમ-પરિવહનમાંથી ડિજિટલ કોપી બતાવવાનો અધિકાર છે. તમને મૂળ દસ્તાવેજ રજૂ કરવા માટે 15-દિવસની વિંડો મળે છે.' } },
        { offense: { en: 'Driving without Insurance', hi: 'बिना बीमा के गाड़ी चलाना', gu: 'વીમા વિના ડ્રાઇવિંગ' }, section: '146/196 MVA', fine: '₹2,000 for first offense', procedure: { en: 'Present a digital copy if available. Driving without valid insurance is a serious offense. The officer has the right to check your insurance status electronically.', hi: 'यदि उपलब्ध हो तो एक डिजिटल प्रति प्रस्तुत करें। बिना वैध बीमा के गाड़ी चलाना एक गंभीर अपराध है। अधिकारी को इलेक्ट्रॉनिक रूप से आपकी बीमा स्थिति की जांच करने का अधिकार है।', gu: 'જો ઉપલબ્ધ હોય તો ડિજિટલ કોપી રજૂ કરો. માન્ય વીમા વિના વાહન ચલાવવું એ ગંભીર ગુનો છે. અધિકારીને તમારી વીમાની સ્થિતિ ઇલેક્ટ્રોનિક રીતે તપાસવાનો અધિકાર છે.' } },
        { offense: { en: 'Overspeeding', hi: 'अधिक गति से गाड़ी चलाना', gu: 'વધુ ઝડપે ડ્રાઇવિંગ' }, section: '183 MVA', fine: '₹1,000 - ₹2,000 for LMV', procedure: { en: 'Fines are often captured by speed cameras and sent via e-challan. If stopped, do not argue about the speed limit; ask for the proof from the speed gun.', hi: 'जुर्माना अक्सर स्पीड कैमरों द्वारा लगाया जाता है और ई-चालान के माध्यम से भेजा जाता है। यदि रोका जाए, तो गति सीमा के बारे में बहस न करें; स्पीड गन से सबूत मांगें।', gu: 'દંડ ઘણીવાર સ્પીડ કેમેરા દ્વારા લગાવવામાં આવે છે અને ઇ-ચલન દ્વારા મોકલવામાં આવે છે. જો રોકવામાં આવે, તો ઝડપ મર્યાદા વિશે દલીલ કરશો નહીં; સ્પીડ ગનમાંથી પુરાવા માંગો.' } },
        { offense: { en: 'Red Light Jumping', hi: 'रेड लाइट जंपिंग', gu: 'રેડ લાઇટ જમ્પિંગ' }, section: '119/177 MVA', fine: '₹1,000 - ₹5,000 and/or license seizure', procedure: { en: 'This is often caught on camera. If stopped by an officer, remain calm. Arguing can lead to higher penalties. Your license can be suspended for 3 months.', hi: 'यह अक्सर कैमरे में कैद हो जाता है। यदि किसी अधिकारी द्वारा रोका जाए, तो शांत रहें। बहस करने से अधिक दंड लग सकता है। आपका लाइसेंस 3 महीने के लिए निलंबित किया जा सकता है।', gu: 'આ ઘણીવાર કેમેરામાં કેદ થાય છે. જો કોઈ અધિકારી દ્વારા રોકવામાં આવે, તો શાંત રહો. દલીલ કરવાથી વધુ દંડ થઈ શકે છે. તમારું લાઇસન્સ 3 મહિના માટે સસ્પેન્ડ કરી શકાય છે.' } },
        { offense: { en: 'Drunken Driving', hi: 'शराब पीकर गाड़ी चलाना', gu: 'નશામાં ડ્રાઇવિંગ' }, section: '185 MVA', fine: '₹10,000 and/or 6 months jail', procedure: { en: 'Cooperate with the breathalyzer test. You can be arrested without a warrant. Police will impound the vehicle. Refusing the test is also an offense. Legal limit is 30mg of alcohol per 100ml of blood.', hi: 'ब्रेथलाइज़र परीक्षण में सहयोग करें। आपको बिना वारंट के गिरफ्तार किया जा सकता है। पुलिस वाहन को जब्त कर लेगी। परीक्षण से इनकार करना भी एक अपराध है। कानूनी सीमा 100 मिलीलीटर रक्त में 30 मिलीग्राम शराब है।', gu: 'બ્રેથલાઇઝર પરીક્ષણમાં સહકાર આપો. તમારી વોરંટ વિના ધરપકડ થઈ શકે છે. પોલીસ વાહન જપ્ત કરશે. પરીક્ષણનો ઇનકાર કરવો એ પણ એક ગુનો છે. કાનૂની મર્યાદા 100 મિલી લોહીમાં 30 મિલિગ્રામ આલ્કોહોલ છે.' } },
        { offense: { en: 'Using mobile while driving', hi: 'गाड़ी चलाते समय मोबाइल का उपयोग करना', gu: 'ડ્રાઇવિંગ કરતી વખતે મોબાઇલનો ઉપયોગ કરવો' }, section: '184 MVA', fine: '₹5,000', procedure: { en: 'Holding a phone for any reason while driving is an offense. This includes calls, texting, or navigation. Use a hands-free mount for navigation. Do not argue if caught.', hi: 'गाड़ी चलाते समय किसी भी कारण से फोन पकड़ना एक अपराध है। इसमें कॉल, टेक्स्टिंग या नेविगेशन शामिल है। नेविगेशन के लिए हैंड्स-फ्री माउंट का उपयोग करें। पकड़े जाने पर बहस न करें।', gu: 'ડ્રાઇવિંગ કરતી વખતે કોઈપણ કારણોસર ફોન પકડવો એ ગુનો છે. આમાં કોલ, ટેક્સ્ટિંગ અથવા નેવિગેશન શામેલ છે. નેવિગેશન માટે હેન્ડ્સ-ફ્રી માઉન્ટનો ઉપયોગ કરો. પકડાય તો દલીલ ન કરો.' } },
        { offense: { en: 'Driving without PUC Certificate', hi: 'बिना PUC प्रमाणपत्र के गाड़ी चलाना', gu: 'પીયુસી પ્રમાણપત્ર વિના ડ્રાઇવિંગ' }, section: '190(2) MVA', fine: '₹10,000', procedure: { en: 'A valid "Pollution Under Control" certificate is mandatory. You can show the digital copy. Traffic police can check its validity online. Failure to produce may lead to license suspension.', hi: 'एक वैध "प्रदूषण नियंत्रण" प्रमाण पत्र अनिवार्य है। आप डिजिटल प्रति दिखा सकते हैं। यातायात पुलिस इसकी वैधता ऑनलाइन जांच सकती है। प्रस्तुत करने में विफलता लाइसेंस निलंबन का कारण बन सकती है।', gu: 'માન્ય "પોલ્યુશન અંડર કંટ્રોલ" પ્રમાણપત્ર ફરજિયાત છે. તમે ડિજિટલ કોપી બતાવી શકો છો. ટ્રાફિક પોલીસ તેની માન્યતા ઓનલાઈન ચકાસી શકે છે. રજૂ કરવામાં નિષ્ફળતા લાઇસન્સ સસ્પેન્શન તરફ દોરી શકે છે.' } },
        { offense: { en: 'Triple Riding on two-wheeler', hi: 'दोपहिया वाहन पर ट्रिपल राइडिंग', gu: 'ટુ-વ્હીલર પર ત્રિપલ રાઇડિંગ' }, section: '128/177 MVA', fine: '₹1,000 and license disqualification', procedure: { en: 'This is a serious safety violation. The officer will issue a challan. It is unsafe and illegal. Do not attempt to bribe the officer.', hi: 'यह एक गंभीर सुरक्षा उल्लंघन है। अधिकारी चालान जारी करेगा। यह असुरक्षित और अवैध है। अधिकारी को रिश्वत देने का प्रयास न करें।', gu: 'આ એક ગંભીર સુરક્ષા ઉલ્લંઘન છે. અધિકારી ચલણ જારી કરશે. તે અસુરક્ષિત અને ગેરકાયદેસર છે. અધિકારીને લાંચ આપવાનો પ્રયાસ કરશો નહીં.' } },
        { offense: { en: 'Obstructing Traffic', hi: 'यातायात में बाधा डालना', gu: 'ટ્રાફિકમાં અવરોધ' }, section: '201 MVA', fine: '₹500', procedure: { en: 'Stopping your vehicle in a way that causes inconvenience or danger to other road users is an offense. Park only in designated areas.', hi: 'अपने वाहन को इस तरह से रोकना कि अन्य सड़क उपयोगकर्ताओं को असुविधा या खतरा हो, एक अपराध है। केवल निर्दिष्ट क्षेत्रों में पार्क करें।', gu: 'તમારા વાહનને એવી રીતે રોકવું કે જે અન્ય માર્ગ વપરાશકર્તાઓ માટે અસુવિધા અથવા ભયનું કારણ બને તે ગુનો છે. ફક્ત નિયુક્ત વિસ્તારોમાં જ પાર્ક કરો.' } },
    ],
    "Maharashtra": [
        { offense: { en: 'Driving without helmet', hi: 'बिना हेलमेट के गाड़ी चलाना', gu: 'હેલ્મેટ વિના ડ્રાઇવિંગ' }, section: '194D MVA', fine: '₹500 and 3-month license suspension', procedure: { en: 'Fine can be paid via e-challan. Pillion riders also must wear a helmet in cities like Mumbai and Pune. Repeated offenses can lead to higher fines.', hi: 'जुर्माना ई-चालान के माध्यम से भरा जा सकता है। मुंबई और पुणे जैसे शहरों में पीछे बैठने वाले को भी हेलमेट पहनना अनिवार्य है। बार-बार अपराध करने पर अधिक जुर्माना लग सकता है।', gu: 'દંડ ઇ-ચલન દ્વારા ભરી શકાય છે. મુંબઈ અને પુણે જેવા શહેરોમાં પાછળ બેસનાર માટે પણ હેલ્મેટ પહેરવું ફરજિયાત છે. વારંવારના ગુનાઓથી વધુ દંડ થઈ શકે છે.' } },
        { offense: { en: 'Using mobile while driving', hi: 'गाड़ी चलाते समय मोबाइल का उपयोग करना', gu: 'ડ્રાઇવિંગ કરતી વખતે મોબાઇલનો ઉપયોગ કરવો' }, section: '184 MVA', fine: '₹5,000', procedure: { en: 'Using a mobile for navigation is also an offense unless it is mounted on a stand. Do not touch the phone while driving. Police are very strict about this rule.', hi: 'नेविगेशन के लिए मोबाइल का उपयोग करना भी एक अपराध है जब तक कि यह स्टैंड पर न लगा हो। गाड़ी चलाते समय फोन को न छुएं। पुलिस इस नियम को लेकर बहुत सख्त है।', gu: 'નેવિગેશન માટે મોબાઇલનો ઉપયોગ કરવો પણ એક ગુનો છે સિવાય કે તે સ્ટેન્ડ પર માઉન્ટ થયેલ હોય. ડ્રાઇવિંગ કરતી વખતે ફોનને સ્પર્શ કરશો નહીં. પોલીસ આ નિયમ અંગે ખૂબ કડક છે.' } },
        { offense: { en: 'Driving without seatbelt', hi: 'बिना सीटबेल्ट के गाड़ी चलाना', gu: 'સીટબેલ્ટ વિના ડ્રાઇવિંગ' }, section: '194B(1) MVA', fine: '₹1,000', procedure: { en: 'The fine is applicable for the driver and all passengers (front and rear) in cities like Mumbai. Always wear a seatbelt.', hi: 'यह जुर्माना मुंबई जैसे शहरों में ड्राइवर और सभी यात्रियों (आगे और पीछे) के लिए लागू है। हमेशा सीटबेल्ट पहनें।', gu: 'આ દંડ મુંબઈ જેવા શહેરોમાં ડ્રાઇવર અને તમામ મુસાફરો (આગળ અને પાછળ) માટે લાગુ છે. હંમેશા સીટબેલ્ટ પહેરો.' } },
        { offense: { en: 'Overspeeding', hi: 'अधिक गति से गाड़ी चलाना', gu: 'વધુ ઝડપે ડ્રાઇવિંગ' }, section: '183 MVA', fine: '₹1,000 - ₹4,000', procedure: { en: 'The fine amount depends on the vehicle type and the speed margin. Ask for evidence from the interceptor vehicle if stopped. Expressways have strict speed monitoring.', hi: 'जुर्माने की राशि वाहन के प्रकार और गति मार्जिन पर निर्भर करती है। यदि रोका जाए तो इंटरसेप्टर वाहन से सबूत मांगें। एक्सप्रेसवे पर गति की सख्त निगरानी होती है।', gu: 'દંડની રકમ વાહનના પ્રકાર અને સ્પીડ માર્જિન પર આધાર રાખે છે. જો રોકવામાં આવે તો ઇન્ટરસેપ્ટર વાહનમાંથી પુરાવા માંગો. એક્સપ્રેસવે પર ગતિનું કડક નિરીક્ષણ છે.' } },
        { offense: { en: 'Blocking Emergency Vehicle', hi: 'आपातकालीन वाहन को रोकना', gu: 'ઇમરજન્સી વાહનને અવરોધિત કરવું' }, section: '194E MVA', fine: '₹10,000', procedure: { en: 'Failing to give way to vehicles like ambulances or fire trucks is a serious offense. Always move to the left and clear the path. It can also lead to license suspension.', hi: 'एम्बुलेंस या फायर ट्रक जैसे वाहनों को रास्ता न देना एक गंभीर अपराध है। हमेशा बाईं ओर हटें और रास्ता साफ करें। इससे लाइसेंस निलंबन भी हो सकता है।', gu: 'એમ્બ્યુલન્સ અથવા ફાયર ટ્રક જેવા વાહનોને રસ્તો ન આપવો એ ગંભીર ગુનો છે. હંમેશા ડાબી બાજુ ખસો અને રસ્તો સાફ કરો. તે લાઇસન્સ સસ્પેન્શન તરફ પણ દોરી શકે છે.' } },
        { offense: { en: 'Wrong Parking / No Parking', hi: 'गलत पार्किंग / नो पार्किंग', gu: 'ખોટી પાર્કિંગ / નો પાર્કિંગ' }, section: '122/177 MVA', fine: '₹500 and towing charges', procedure: { en: 'Police can tow your vehicle from a no-parking zone. You must pay the fine plus towing charges at the designated traffic police station to release your vehicle.', hi: 'पुलिस नो-पार्किंग जोन से आपके वाहन को टो कर सकती है। आपको अपने वाहन को छुड़ाने के लिए निर्धारित यातायात पुलिस स्टेशन पर जुर्माना और टोइंग शुल्क का भुगतान करना होगा।', gu: 'પોલીસ નો-પાર્કિંગ ઝોનમાંથી તમારા વાહનને ટો કરી શકે છે. તમારે તમારા વાહનને છોડાવવા માટે નિયુક્ત ટ્રાફિક પોલીસ સ્ટેશન પર દંડ અને ટોઇંગ ચાર્જ ચૂકવવા પડશે.' } },
        { offense: { en: 'Drunken Driving', hi: 'शराब पीकर गाड़ी चलाना', gu: 'નશામાં ડ્રાઇવિંગ' }, section: '185 MVA', fine: '₹10,000 and/or imprisonment', procedure: { en: 'Strictly enforced. Vehicle will be impounded. You will be arrested and required to appear in court. Refusing a breathalyzer test leads to legal action.', hi: 'सख्ती से लागू। वाहन जब्त कर लिया जाएगा। आपको गिरफ्तार किया जाएगा और अदालत में पेश होना होगा। ब्रेथलाइज़र परीक्षण से इनकार करने पर कानूनी कार्रवाई होगी।', gu: 'કડક રીતે લાગુ. વાહન જપ્ત કરવામાં આવશે. તમારી ધરપકડ કરવામાં આવશે અને કોર્ટમાં હાજર રહેવું પડશે. બ્રેથલાઇઝર પરીક્ષણનો ઇનકાર કરવાથી કાનૂની કાર્યવાહી થશે.' } },
        { offense: { en: 'Lane Cutting / Indiscipline', hi: 'लेन कटिंग / अनुशासनहीनता', gu: 'લેન કટિંગ / બિનશಿಸ್ત' }, section: '194A MVA', fine: '₹500', procedure: { en: 'Changing lanes without proper indication or weaving through traffic is an offense. Maintain your lane, especially on highways and bridges.', hi: 'बिना उचित संकेत के लेन बदलना या यातायात के बीच से निकलना एक अपराध है। अपनी लेन बनाए रखें, खासकर राजमार्गों और पुलों पर।', gu: 'યોગ્ય સંકેત વિના લેન બદલવી અથવા ટ્રાફિકમાંથી પસાર થવું એ ગુનો છે. તમારી લેન જાળવી રાખો, ખાસ કરીને હાઇવે અને પુલ પર.' } },
        { offense: { en: 'Driving without Insurance', hi: 'बिना बीमा के गाड़ी चलाना', gu: 'વીમા વિના ડ્રાઇવિંગ' }, section: '146/196 MVA', fine: '₹2,000', procedure: { en: 'Third-party insurance is mandatory. Show digital copy from mParivahan or DigiLocker. Police can verify it online instantly.', hi: 'थर्ड-पार्टी बीमा अनिवार्य है। एम-परिवहन या डिजिलॉकर से डिजिटल कॉपी दिखाएं। पुलिस इसे तुरंत ऑनलाइन सत्यापित कर सकती है।', gu: 'થર્ડ-પાર્ટી વીમો ફરજિયાત છે. એમ-પરિવહન અથવા ડીજીલોકર પરથી ડિજિટલ કોપી બતાવો. પોલીસ તેને તરત જ ઓનલાઈન ચકાસી શકે છે.' } },
    ],
    "Gujarat": [
      { offense: { en: 'Driving without helmet', hi: 'बिना हेलमेट के गाड़ी चलाना', gu: 'હેલ્મેટ વિના ડ્રાઇવિંગ' }, section: '194D MVA', fine: '₹500', procedure: { en: 'Pay online via e-challan portal. You can present your documents via DigiLocker. Both rider and pillion must wear helmets.', hi: 'ई-चालान पोर्टल के माध्यम से ऑनलाइन भुगतान करें। आप अपने दस्तावेज़ डिजिलॉकर के माध्यम से प्रस्तुत कर सकते हैं। राइडर और पिलियन दोनों को हेलमेट पहनना चाहिए।', gu: 'ઇ-ચલન પોર્ટલ દ્વારા ઓનલાઈન ચૂકવણી કરો. તમે તમારા દસ્તાવેજો ડીજીલોકર દ્વારા રજૂ કરી શકો છો. રાઇડર અને પિલિયન બંનેએ હેલ્મેટ પહેરવું આવશ્યક છે.' } },
      { offense: { en: 'Driving without seatbelt', hi: 'बिना सीटबेल्ट के गाड़ी चलाना', gu: 'સીટબેલ્ટ વિના ડ્રાઇવિંગ' }, section: '194B(1) MVA', fine: '₹500', procedure: { en: 'Pay online via e-challan portal. The rule applies to the driver and co-passenger in the front seat.', hi: 'ई-चालान पोर्टल के माध्यम से ऑनलाइन भुगतान करें। यह नियम ड्राइवर और सामने की सीट पर बैठे सह-यात्री पर लागू होता है।', gu: 'ઇ-ચલન પોર્ટલ દ્વારા ઓનલાઈન ચૂકવણી કરો. આ નિયમ ડ્રાઇવર અને આગળની સીટ પર બેઠેલા સહ-મુસાફરને લાગુ પડે છે.' } },
      { offense: { en: 'Using mobile while driving', hi: 'गाड़ी चलाते समय मोबाइल का उपयोग करना', gu: 'ડ્રાઇવિંગ કરતી વખતે મોબાઇલનો ઉપયોગ કરવો' }, section: '184 MVA', fine: '₹1,000 for first offense', procedure: { en: 'Police can issue a challan. Avoid arguing. It is safer to park your vehicle to take a call. Using phone for navigation is only allowed in a holder.', hi: 'पुलिस चालान जारी कर सकती है। बहस करने से बचें। कॉल लेने के लिए अपने वाहन को पार्क करना सुरक्षित है। नेविगेशन के लिए फोन का उपयोग केवल होल्डर में ही किया जा सकता है।', gu: 'પોલીસ ચલણ જારી કરી શકે છે. દલીલ કરવાનું ટાળો. કોલ લેવા માટે તમારા વાહનને પાર્ક કરવું વધુ સુરક્ષિત છે. નેવિગેશન માટે ફોનનો ઉપયોગ ફક્ત હોલ્ડરમાં જ કરવાની મંજૂરી છે.' } },
      { offense: { en: 'Triple Riding on two-wheeler', hi: 'दोपहिया वाहन पर ट्रिपल राइडिंग', gu: 'ટુ-વ્હીલર પર ત્રિપલ રાઇડિંગ' }, section: '128/177 MVA', fine: '₹100', procedure: { en: 'This is a common offense. The officer will issue a challan. It is unsafe and illegal. Do not carry more than one pillion rider.', hi: 'यह एक आम अपराध है। अधिकारी चालान जारी करेगा। यह असुरक्षित और अवैध है। एक से अधिक पिलियन राइडर न ले जाएं।', gu: 'આ એક સામાન્ય ગુનો છે. અધિકારી ચલણ જારી કરશે. તે અસુરક્ષિત અને ગેરકાયદેસર છે. એક કરતાં વધુ પિલિયન રાઇડર ન રાખો.' } },
      { offense: { en: 'Driving without PUC certificate', hi: 'बिना PUC प्रमाणपत्र के गाड़ी चलाना', gu: 'પીયુસી પ્રમાણપત્ર વિના ડ્રાઇવિંગ' }, section: '190(2) MVA', fine: '₹1,000', procedure: { en: 'A valid "Pollution Under Control" certificate is mandatory. You can show the digital copy. Traffic police can check its validity online.', hi: 'एक वैध "प्रदूषण नियंत्रण" प्रमाण पत्र अनिवार्य है। आप डिजिटल प्रति दिखा सकते हैं। यातायात पुलिस इसकी वैधता ऑनलाइन जांच सकती है।', gu: 'માન્ય "પોલ્યુશન અંડર કંટ્રોલ" પ્રમાણપત્ર ફરજિયાત છે. તમે ડિજિટલ કોપી બતાવી શકો છો. ટ્રાફિક પોલીસ તેની માન્યતા ઓનલાઈન ચકાસી શકે છે.' } },
      { offense: { en: 'Wrong Side Driving', hi: 'गलत साइड ड्राइविंग', gu: 'ખોટી સાઇડ ડ્રાઇવિંગ' }, section: '119/177 MVA', fine: '₹1,500 - ₹5,000', procedure: { en: 'Driving against the flow of traffic is extremely dangerous and carries a heavy fine. Follow traffic signs and road markings.', hi: 'यातायात के प्रवाह के खिलाफ गाड़ी चलाना बेहद खतरनाक है और इस पर भारी जुर्माना लगता है। यातायात संकेतों और सड़क चिह्नों का पालन करें।', gu: 'ટ્રાફિકના પ્રવાહની વિરુદ્ધ ડ્રાઇવિંગ કરવું અત્યંત જોખમી છે અને તેના પર ભારે દંડ છે. ટ્રાફિક સંકેતો અને રસ્તાના નિશાનોનું પાલન કરો.' } },
      { offense: { en: 'Fancy/Improper Number Plate', hi: 'फैंसी/अनुचित नंबर प्लेट', gu: 'ફેન્સી/અયોગ્ય નંબર પ્લેટ' }, section: 'CMVR 105(2)/177 MVA', fine: '₹1,000', procedure: { en: 'Number plates must be in the prescribed format (HSRP - High Security Registration Plate). Using stylish fonts or designs is illegal.', hi: 'नंबर प्लेट निर्धारित प्रारूप (HSRP - हाई सिक्योरिटी रजिस्ट्रेशन प्लेट) में होनी चाहिए। स्टाइलिश फोंट या डिजाइन का उपयोग करना अवैध है।', gu: 'નંબર પ્લેટ નિર્ધારિત ફોર્મેટમાં (HSRP - હાઇ સિક્યુરિટી રજીસ્ટ્રેશન પ્લેટ) હોવી આવશ્યક છે. સ્ટાઇલિશ ફોન્ટ્સ અથવા ડિઝાઇનનો ઉપયોગ કરવો ગેરકાયદેસર છે.' } },
      { offense: { en: 'Driving without License', hi: 'बिना लाइसेंस के गाड़ी चलाना', gu: 'લાયસન્સ વિના ડ્રાઇવિંગ' }, section: '3/181 MVA', fine: '₹2,000 for 2-wheeler, ₹3,000 for LMV', procedure: { en: 'A valid driving license is mandatory. If you cannot produce it, the vehicle may be detained. You can show a digital copy from DigiLocker.', hi: 'एक वैध ड्राइविंग लाइसेंस अनिवार्य है। यदि आप इसे प्रस्तुत नहीं कर सकते हैं, तो वाहन को हिरासत में लिया जा सकता है। आप डिजिलॉकर से एक डिजिटल प्रति दिखा सकते हैं।', gu: 'માન્ય ડ્રાઇવિંગ લાઇસન્સ ફરજિયાત છે. જો તમે તેને રજૂ ન કરી શકો, તો વાહનને અટકાયતમાં લઈ શકાય છે. તમે ડીજીલોકર પરથી ડિજિટલ કોપી બતાવી શકો છો.' } },
      { offense: { en: 'Red Light Jumping', hi: 'रेड लाइट जंपिंग', gu: 'રેડ લાઇટ જમ્પિંગ' }, section: '119/177 MVA', fine: '₹1,000 - ₹5,000', procedure: { en: 'Stopping beyond the stop line or crossing when the light is red. This is monitored by cameras. Pay the fine online to avoid complications.', hi: 'स्टॉप लाइन से आगे रुकना या बत्ती लाल होने पर पार करना। इसकी निगरानी कैमरों द्वारा की जाती है। जटिलताओं से बचने के लिए ऑनलाइन जुर्माना भरें।', gu: 'સ્ટોપ લાઇનથી આગળ રોકાવું અથવા લાઇટ લાલ હોય ત્યારે પાર કરવું. આ કેમેરા દ્વારા મોનિટર કરવામાં આવે છે. ગૂંચવણો ટાળવા માટે ઓનલાઈન દંડ ભરો.' } },
    ],
    "Karnataka": [
        { offense: { en: 'Driving without helmet', hi: 'बिना हेलमेट के गाड़ी चलाना', gu: 'હેલ્મેટ વિના ડ્રાઇવિંગ' }, section: '194D MVA', fine: '₹500', procedure: { en: 'Both rider and pillion must wear helmets with ISI mark. Pay the fine through the official traffic police portal or at designated centers.', hi: 'राइडर और पिलियन दोनों को ISI मार्क वाला हेलमेट पहनना होगा। आधिकारिक ट्रैफिक पुलिस पोर्टल या निर्दिष्ट केंद्रों के माध्यम से जुर्माना भरें।', gu: 'રાઇડર અને પિલિયન બંનેએ ISI માર્કવાળા હેલ્મેટ પહેરવા આવશ્યક છે. સત્તાવાર ટ્રાફિક પોલીસ પોર્ટલ અથવા નિયુક્ત કેન્દ્રો દ્વારા દંડ ભરો.' } },
        { offense: { en: 'Driving without seatbelt', hi: 'बिना सीटबेल्ट के गाड़ी चलाना', gu: 'સીટબેલ્ટ વિના ડ્રાઇવિંગ' }, section: '194B(1) MVA', fine: '₹500', procedure: { en: 'E-challan will be issued. The rule is strictly enforced in major cities like Bengaluru for all occupants of the car, including rear passengers.', hi: 'ई-चालान जारी किया जाएगा। यह नियम बेंगलुरु जैसे प्रमुख शहरों में कार के सभी यात्रियों, जिसमें पीछे के यात्री भी शामिल हैं, के लिए सख्ती से लागू किया जाता है।', gu: 'ઇ-ચલન જારી કરવામાં આવશે. આ નિયમ બેંગલુરુ જેવા મુખ્ય શહેરોમાં કારના તમામ મુસાફરો, પાછળના મુસાફરો સહિત, માટે સખત રીતે લાગુ કરવામાં આવે છે.' } },
        { offense: { en: 'Drunken Driving', hi: 'शराब पीकर गाड़ी चलाना', gu: 'નશામાં ડ્રાઇવિંગ' }, section: '185 MVA', fine: '₹10,000 and/or imprisonment', procedure: { en: 'Vehicle will be impounded, and license suspended. You will have to appear in court. Cooperate with the police during the process. Do not refuse the breathalyzer test.', hi: 'वाहन को जब्त कर लिया जाएगा, और लाइसेंस निलंबित कर दिया जाएगा। आपको अदालत में पेश होना होगा। प्रक्रिया के दौरान पुलिस के साथ सहयोग करें। ब्रेथलाइज़र परीक्षण से इनकार न करें।', gu: 'વાહન જપ્ત કરવામાં આવશે, અને લાયસન્સ સસ્પેન્ડ કરવામાં આવશે. તમારે કોર્ટમાં હાજર રહેવું પડશે. પ્રક્રિયા દરમિયાન પોલીસને સહકાર આપો. બ્રેથલાઇઝર પરીક્ષણનો ઇનકાર કરશો નહીં.' } },
        { offense: { en: 'Wrong Parking', hi: 'गलत पार्किंग', gu: 'ખોટી પાર્કિંગ' }, section: '122/177 MVA', fine: '₹500 - ₹1,000', procedure: { en: 'Police may tow the vehicle from a "No Parking" zone. In Bengaluru, "Tiger" towing vehicles are used. You will have to pay the fine plus towing charges to get it back.', hi: 'पुलिस "नो पार्किंग" जोन से वाहन को टो कर सकती है। बेंगलुरु में, "टाइगर" टोइंग वाहनों का उपयोग किया जाता है। इसे वापस पाने के लिए आपको जुर्माना और टोइंग शुल्क का भुगतान करना होगा।', gu: 'પોલીસ "નો પાર્કિંગ" ઝોનમાંથી વાહન ટો કરી શકે છે. બેંગલુરુમાં, "ટાઇગર" ટોઇંગ વાહનોનો ઉપયોગ થાય છે. તેને પાછું મેળવવા માટે તમારે દંડ અને ટોઇંગ ચાર્જ ચૂકવવા પડશે.' } },
        { offense: { en: 'Using mobile while driving', hi: 'गाड़ी चलाते समय मोबाइल का उपयोग करना', gu: 'ડ્રાઇવિંગ કરતી વખતે મોબાઇલનો ઉપયોગ કરવો' }, section: '184 MVA', fine: '₹1,500 - ₹3,000', procedure: { en: 'Strictly prohibited. This includes holding the phone between your helmet and head. Use of Bluetooth devices for calls is also not advised.', hi: 'सख्ती से निषिद्ध। इसमें फोन को हेलमेट और सिर के बीच रखना भी शामिल है। कॉल के लिए ब्लूटूथ उपकरणों का उपयोग भी उचित नहीं है।', gu: 'કડક પ્રતિબંધિત. આમાં ફોનને તમારા હેલ્મેટ અને માથા વચ્ચે પકડી રાખવાનો પણ સમાવેશ થાય છે. કોલ્સ માટે બ્લુટુથ ઉપકરણોનો ઉપયોગ પણ સલાહભર્યું નથી.' } },
        { offense: { en: 'Rash and Negligent Driving', hi: 'लापरवाही और उपेक्षा से गाड़ी चलाना', gu: 'બેદરકારી અને ઉપેક્ષાપૂર્વક ડ્રાઇવિંગ' }, section: '184 MVA', fine: '₹1,000 - ₹5,000', procedure: { en: 'Includes acts like speeding, sudden braking, zig-zag driving. It is a serious offense that endangers others. Police can suspend your license.', hi: 'इसमें तेज गति, अचानक ब्रेक लगाना, ज़िग-ज़ैग ड्राइविंग जैसे कार्य शामिल हैं। यह एक गंभीर अपराध है जो दूसरों को खतरे में डालता है। पुलिस आपका लाइसेंस निलंबित कर सकती है।', gu: 'આમાં સ્પીડિંગ, અચાનક બ્રેકિંગ, ઝિગ-ઝેગ ડ્રાઇવિંગ જેવી ક્રિયાઓનો સમાવેશ થાય છે. તે એક ગંભીર ગુનો છે જે અન્યને જોખમમાં મૂકે છે. પોલીસ તમારું લાઇસન્સ સસ્પેન્ડ કરી શકે છે.' } },
        { offense: { en: 'Driving on Footpath', hi: 'फुटपाथ पर गाड़ी चलाना', gu: 'ફૂટપાથ પર ડ્રાઇવિંગ' }, section: 'R.R.R 17/177 MVA', fine: '₹500', procedure: { en: 'Driving any vehicle on a footpath or cycle track is illegal and dangerous for pedestrians. It is strictly enforced in cities.', hi: 'किसी भी वाहन को फुटपाथ या साइकिल ट्रैक पर चलाना अवैध और पैदल चलने वालों के लिए खतरनाक है। इसे शहरों में सख्ती से लागू किया जाता है।', gu: 'કોઈપણ વાહનને ફૂટપાથ અથવા સાયકલ ટ્રેક પર ચલાવવું ગેરકાયદેસર અને પદયાત્રીઓ માટે જોખમી છે. શહેરોમાં તેનો કડક અમલ કરવામાં આવે છે.' } },
        { offense: { en: 'Driving without License', hi: 'बिना लाइसेंस के गाड़ी चलाना', gu: 'લાયસન્સ વિના ડ્રાઇવિંગ' }, section: '3/181 MVA', fine: '₹1,000 for 2-wheeler, ₹2,000 for LMV', procedure: { en: 'You must carry a valid driving license. Digital copies from official apps like DigiLocker are accepted. Police have the right to detain the vehicle if no license is produced.', hi: 'आपको एक वैध ड्राइविंग लाइसेंस ले जाना होगा। डिजिलॉकर जैसे आधिकारिक ऐप्स से डिजिटल प्रतियां स्वीकार की जाती हैं। यदि कोई लाइसेंस प्रस्तुत नहीं किया जाता है तो पुलिस को वाहन को हिरासत में लेने का अधिकार है।', gu: 'તમારે માન્ય ડ્રાઇવિંગ લાઇસન્સ સાથે રાખવું આવશ્યક છે. ડીજીલોકર જેવી સત્તાવાર એપ્લિકેશન્સમાંથી ડિજિટલ નકલો સ્વીકારવામાં આવે છે. જો કોઈ લાઇસન્સ રજૂ કરવામાં ન આવે તો પોલીસને વાહનને અટકાયતમાં લેવાનો અધિકાર છે.' } },
        { offense: { en: 'Disobeying Traffic Signals', hi: 'यातायात संकेतों का उल्लंघन', gu: 'ટ્રાફિક સંકેતોનો અનાદર' }, section: '119/177 MVA', fine: '₹500', procedure: { en: 'This includes not following signals from traffic police officers or automated signals. It is a safety risk and can lead to accidents.', hi: 'इसमें यातायात पुलिस अधिकारियों या स्वचालित संकेतों के संकेतों का पालन न करना शामिल है। यह एक सुरक्षा जोखिम है और इससे दुर्घटनाएं हो सकती हैं।', gu: 'આમાં ટ્રાફિક પોલીસ અધિકારીઓ અથવા સ્વચાલિત સંકેતોના સંકેતોનું પાલન ન કરવાનો સમાવેશ થાય છે. તે એક સુરક્ષા જોખમ છે અને અકસ્માતો તરફ દોરી શકે છે.' } },
    ]
};


export const RIGHTS_LIBRARY: RightCategory[] = [
    {
        title: { en: "Rights as a Citizen", hi: "एक नागरिक के रूप में अधिकार", gu: "એક નાગરિક તરીકે અધિકારો" },
        rights: [
            { title: { en: "Right to Ask for ID", hi: "आईडी मांगने का अधिकार", gu: "આઈડી માંગવાનો અધિકાર" }, description: { en: "You have the right to politely ask a police officer for their identification.", hi: "आपको विनम्रता से एक पुलिस अधिकारी से उनकी पहचान पूछने का अधिकार है।", gu: "તમને નમ્રતાપૂર્વક પોલીસ અધિકારીને તેમની ઓળખ પૂછવાનો અધિકાર છે." } },
            { title: { en: "Right to Know the Reason for Detention", hi: "हिरासत का कारण जानने का अधिकार", gu: "અટકાયતનું કારણ જાણવાનો અધિકાર" }, description: { en: "If you are being detained, you have the right to be informed of the grounds for your arrest.", hi: "यदि आपको हिरासत में लिया जा रहा है, तो आपको अपनी गिरफ्तारी के आधारों के बारे में सूचित किए जाने का अधिकार है।", gu: "જો તમારી અટકાયત કરવામાં આવી રહી છે, તો તમને તમારી ધરપકડના કારણો વિશે જાણ કરવાનો અધિકાર છે." } },
        ]
    },
    {
        title: { en: "Rules Police Must Follow", hi: "पुलिस को पालन करने वाले नियम", gu: "પોલીસે પાલન કરવાના નિયમો" },
        rights: [
            { title: { en: "Must Be in Uniform", hi: "वर्दी में होना चाहिए", gu: "ગણવેશમાં હોવું આવશ્યક છે" }, description: { en: "A police officer must be in uniform to issue a traffic challan.", hi: "एक पुलिस अधिकारी को ट्रैफिक चालान जारी करने के लिए वर्दी में होना चाहिए।", gu: "ટ્રાફિક ચલણ જારી કરવા માટે પોલીસ અધિકારી ગણવેશમાં હોવા જોઈએ." } },
            { title: { en: "Cannot Demand Cash Bribes", hi: "नकद रिश्वत की मांग नहीं कर सकते", gu: "રોકડ લાંચની માંગ કરી શકતા નથી" }, description: { en: "It is illegal for an officer to demand a cash payment without an official challan or receipt. Fines should be paid through official channels.", hi: "एक अधिकारी के लिए आधिकारिक चालान या रसीद के बिना नकद भुगतान की मांग करना अवैध है। जुर्माना आधिकारिक चैनलों के माध्यम से भुगतान किया जाना चाहिए।", gu: "અધિકારી માટે સત્તાવાર ચલણ અથવા રસીદ વિના રોકડ ચુકવણીની માંગ કરવી ગેરકાયદેસર છે. દંડ સત્તાવાર ચેનલો દ્વારા ચૂકવવો જોઈએ." } },
        ]
    }
];